/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServiciiRouteImport } from './routes/servicii'
import { Route as ProduseRouteImport } from './routes/produse'
import { Route as MontareRouteImport } from './routes/montare'
import { Route as GdprRouteImport } from './routes/gdpr'
import { Route as DespreRouteImport } from './routes/despre'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfidentialitateRouteImport } from './routes/confidentialitate'
import { Route as AnpcRouteImport } from './routes/anpc'
import { Route as IndexRouteImport } from './routes/index'

const ServiciiRoute = ServiciiRouteImport.update({
  id: '/servicii',
  path: '/servicii',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduseRoute = ProduseRouteImport.update({
  id: '/produse',
  path: '/produse',
  getParentRoute: () => rootRouteImport,
} as any)
const MontareRoute = MontareRouteImport.update({
  id: '/montare',
  path: '/montare',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRoute = GdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const DespreRoute = DespreRouteImport.update({
  id: '/despre',
  path: '/despre',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialitateRoute = ConfidentialitateRouteImport.update({
  id: '/confidentialitate',
  path: '/confidentialitate',
  getParentRoute: () => rootRouteImport,
} as any)
const AnpcRoute = AnpcRouteImport.update({
  id: '/anpc',
  path: '/anpc',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anpc': typeof AnpcRoute
  '/confidentialitate': typeof ConfidentialitateRoute
  '/contact': typeof ContactRoute
  '/despre': typeof DespreRoute
  '/gdpr': typeof GdprRoute
  '/montare': typeof MontareRoute
  '/produse': typeof ProduseRoute
  '/servicii': typeof ServiciiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anpc': typeof AnpcRoute
  '/confidentialitate': typeof ConfidentialitateRoute
  '/contact': typeof ContactRoute
  '/despre': typeof DespreRoute
  '/gdpr': typeof GdprRoute
  '/montare': typeof MontareRoute
  '/produse': typeof ProduseRoute
  '/servicii': typeof ServiciiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anpc': typeof AnpcRoute
  '/confidentialitate': typeof ConfidentialitateRoute
  '/contact': typeof ContactRoute
  '/despre': typeof DespreRoute
  '/gdpr': typeof GdprRoute
  '/montare': typeof MontareRoute
  '/produse': typeof ProduseRoute
  '/servicii': typeof ServiciiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anpc'
    | '/confidentialitate'
    | '/contact'
    | '/despre'
    | '/gdpr'
    | '/montare'
    | '/produse'
    | '/servicii'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anpc'
    | '/confidentialitate'
    | '/contact'
    | '/despre'
    | '/gdpr'
    | '/montare'
    | '/produse'
    | '/servicii'
  id:
    | '__root__'
    | '/'
    | '/anpc'
    | '/confidentialitate'
    | '/contact'
    | '/despre'
    | '/gdpr'
    | '/montare'
    | '/produse'
    | '/servicii'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnpcRoute: typeof AnpcRoute
  ConfidentialitateRoute: typeof ConfidentialitateRoute
  ContactRoute: typeof ContactRoute
  DespreRoute: typeof DespreRoute
  GdprRoute: typeof GdprRoute
  MontareRoute: typeof MontareRoute
  ProduseRoute: typeof ProduseRoute
  ServiciiRoute: typeof ServiciiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicii': {
      id: '/servicii'
      path: '/servicii'
      fullPath: '/servicii'
      preLoaderRoute: typeof ServiciiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produse': {
      id: '/produse'
      path: '/produse'
      fullPath: '/produse'
      preLoaderRoute: typeof ProduseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/montare': {
      id: '/montare'
      path: '/montare'
      fullPath: '/montare'
      preLoaderRoute: typeof MontareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr': {
      id: '/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despre': {
      id: '/despre'
      path: '/despre'
      fullPath: '/despre'
      preLoaderRoute: typeof DespreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialitate': {
      id: '/confidentialitate'
      path: '/confidentialitate'
      fullPath: '/confidentialitate'
      preLoaderRoute: typeof ConfidentialitateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anpc': {
      id: '/anpc'
      path: '/anpc'
      fullPath: '/anpc'
      preLoaderRoute: typeof AnpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnpcRoute: AnpcRoute,
  ConfidentialitateRoute: ConfidentialitateRoute,
  ContactRoute: ContactRoute,
  DespreRoute: DespreRoute,
  GdprRoute: GdprRoute,
  MontareRoute: MontareRoute,
  ProduseRoute: ProduseRoute,
  ServiciiRoute: ServiciiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
